version: "3.7"
services:
    show:
        image: haifengat/show_kline
        container_name: show_kline
        restart: always
        ports: 
            # 宿主端口
            - 8080:8080
        environment:
            - TZ=Asia/Shanghai
            - Port=8080
            # 运行模式 dev/prod/test
            - RunMode=dev
            # postgres  future_min配置
            - pgConfig=postgres://postgres:123456@172.19.129.98:5432/postgres?sslmode=disable
